name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install uv pytest pytest-cov pyyaml
          make install

      - name: Run linter and pytest
        run: |
          make lint
          python -m pytest tests/ -v --cov=gendiff --cov-report=xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=KlyaksaOFF_python-project-50
            -Dsonar.organization=klyaksaoff
            -Dsonar.python.coverage.reportPaths=coverage.xml